#!/bin/bash

userName=$(git config user.name)
branches=$(git branch  | while read line
do
	count="$count"
	count=$((count + 1))
	echo "Local: $line"
	
done 
)
#remoteFilter = ""
if [ "$1" != "" ]
	then
	remoteFilter="$1"
	else
	remoteFilter="$userName"
fi


remoteBranches=$(git branch -a | grep -i "$remoteFilter" | grep remotes | while read line
do
	count="$count"
	count=$((count + 1))
	echo ${line/remotes\//Remote: }
#	echo "\n"
	
done )

allBranches="$branches
$remoteBranches"

if [ "$1" != "" ]
	then
	echo "filtered by $@"
	for filter in "$@"
	do
		allBranches=$(echo "$allBranches" | grep -i "$filter"  )
	done
fi


allBranches=$(echo "$allBranches" | while read line
do
	count="$count"
	count=$((count + 1))
	echo "$count $line\n"
	
done)

echo -e $allBranches
echo 'Select the branch you would like to check out:'

read userInput

if [ "$userInput" = "q" ]
	then
	
	echo 'quiting'
	exit 0
fi

selection=$(echo -e $allBranches | grep "^[[:space:]]*$userInput ")

branchType=$(echo $selection | awk '{print $2}')
branchName=$(echo $selection | awk '{print $3}')


if [ $branchType = "Remote:" ]
	then 
	echo "$branchName is a remote branch"
	read -p "Type b to create a new local branch or h to checkout the headless revision: " -e -i b coType

	if [ $coType = "b" ]
		then 
		git checkout ${branchName/origin\//}
		exit 0

		
	fi
	 
fi
git checkout $branchName

	