#!/bin/bash

if [[ "$1" =~ [0-9]{5} ]]; then
	git commit --amend -m "$(git log --pretty='format:%B' -1 | sed -e "s/[0-9]\{5\}/$1/")"
	echo "New commit message:"
	git log --pretty='format:%B' -1
else
	echo "Your first argument \"$1\" is not a valid bug number."
fi

