#!/apps/homebrew/bin/node

/**
 * Module dependencies.
 */

var express = require('./node_modules/express');
var logger = require('./node_modules/morgan');
var app = express();

// log requests
app.use(logger('dev'));

// express on its own has no notion
// of a "file". The express.static()
// middleware checks for a file matching
// the `req.path` within the directory
// that you pass it. In this case "GET /js/app.js"
// will look for "./public/js/app.js".

if( ! process.argv[2] ){
	throw 'First paramether is required (try "serveStatic $(pwd)")';
}

var listenPort = process.argv[3] || 3000;

app.use(express.static(process.argv[2]));

// if you wanted to "prefix" you may use
// the mounting feature of Connect, for example
// "GET /static/js/app.js" instead of "GET /js/app.js".
// The mount-path "/static" is simply removed before
// passing control to the express.static() middleware,
// thus it serves the file correctly by ignoring "/static"
//app.use('/static', express.static(__dirname + '/public'));

// if for some reason you want to serve files from
// several directories, you can use express.static()
// multiple times! Here we're passing "./public/css",
// this will allow "GET /style.css" instead of "GET /css/style.css":
//app.use(express.static(__dirname + '/public/css'));

app.listen(listenPort);
console.log("serviing files from", process.argv[2]);
console.log('listening on port', listenPort);
console.log('try:');
console.log('  GET /index.html');
/*console.log('  GET /js/app.js');
console.log('  GET /css/style.css');*/
