#!/bin/bash -e
remote=$(git remote | egrep '^public|origin$' | head -1)
for var in "$@"
do
	git branch -rD $remote/$var
	git branch -D $var
done

git push $remote --delete "$@"
exitCode="$?"
if [[ $exitCode != "0" ]] 
then
	for var in "$@"
	do
		git push $remote --delete $var
	done
fi

